# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: postgres_ml_db
      conn_type: postgres
      conn_host: localhost
      conn_schema: postgres
      conn_login: postgres
      conn_password: postgres
      conn_port: 5433
  pools: []
  variables:
    - variable_name: DATABASE_URL
      variable_value: postgresql://postgres:postgres@localhost:5433/postgres
    - variable_name: ENV
      variable_value: development
